name: Build WebGL

on:
  workflow_dispatch:
  push:
    branches:
      - PRE_PRODUCCION
      - PRODUCCION

jobs:
  build-webgl:
    uses: ./.github/workflows/build-core.yml
    with:
      unityVersion: 6000.2.10f1
      buildTarget: WebGL
      environmentName: DES
      publishToItch: true
      itchioChannel: pax16/roguelike:webgl
      sendToDiscord: true
    secrets: inherit