name: Example - Build Windows

on:
  push:
    branches: [main]

jobs:
  build:
    uses: tu-org/unity-ci-templates/.github/workflows/build-windows.yml@main
    with:
      unityVersion: 2022.3.10f1
      environmentName: DES
      sendToDiscord: true
    secrets: inherit
